### ISSUE TITLE
New release for phpBB 3.3. compatibility

### ISSUE THREAD

**Issue by Crizz0** [gn36/phpbb-ext-firstpostedit#14]
The latest version 1.2.2 does not contain the necessary changes in the https://github.com/gn36/phpbb-ext-firstpostedit/blob/master/config/services.yml to create compatibility with phpBB 3.3.x

I think a new release should be created.

**Comment by Gpinpin** [comment]
Hello
Do you plan to make a modification for versions 3.3.9 and future?
A+

**Comment by Crizz0** [comment]
What is not working with 3.3.9 and newer?

**Comment by Gpinpin** [comment]
No, I'm just asking if it can be installed in version 3.3.9 and if it works. This following the message saying that we must redo an extension (@Crizz0)

**Comment by Crizz0** [comment]
The latest Release v1.3.0 is used by myself with 3.3.9.

Regards

**Comment by Gpinpin** [comment]
Sorry, I just saw that you asked the question.
Ah ok then I will test it thank you

**Comment by Crizz0** [comment]
Solved via: https://github.com/gn36/phpbb-ext-firstpostedit/releases/tag/v1.3.0
